### PR TITLE
Added a Docker support and fixed non-backwards compatability issue with 'Network' library.

### PR DESCRIPTION
**Pull request by TheOptik**
- Added a more concrete version of the 'Network' library to the cabal file, since newer verisons do not seem to be backwards compatible.

- Added a 'Dockerfile' to the repository as well as instructions on how to use it to the 'README.md'

### CODE REVIEW

**Comment by BartMassey** [comment]
Thanks very much! Really appreciate this.

Do you have any interest in patching this to work with the new `Network`? If not I'll probably take a look at it, but my Haskell is pretty rusty (pun intended) at this point.

**Comment by TheOptik** [comment]
My pleasure, i am glad you like the contribution!
I wanted to re-visit a project based on a class you gave at FHWS in 2017 and saw that the hosted instance under "imcs.svcs.cs.pdx.edu" was no longer up and running (and probably hadn't been for some time).
So i wanted to host my own instance and docker just seemed like a good way of doing that.

sadly i am a complete beginner at haskell and probably won't be able to patch the code to work with the newer versions.
I honestly just followed the errors reported by ghc until i found what was wrong.

**Comment by BartMassey** [comment]
Much appreciated. Was nice having you in class back when. Let me know if there are other issues — I regret having written that thing in Haskell these days.

**Comment by TheOptik** [comment]
It was entirely my pleasure, it was a really great class.
The server is running  very niceley so far, but i will happily report back if i find anything in the future.

**Pull request merged**
